server:
  port: 9501
  servlet:
    context-path: /api/employe-service
  
spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/EmployeeModule
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  application:
    name: Employee-Module